services:
  dots-game:
    image: dots-and-boxes:local
    restart: unless-stopped
    container_name: dots-game
    command: bash -c 'cd /usr/src/app/server && node index.js'
    volumes:
      - ../../.:/usr/src/app
    ports:
      - "5001:5001"
    environment:
      - PORT=5001